name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build
        run: npm install && npm run build
      - name: Automated Version Bump
        run: npm version patch -m "[RELEASE] %s"
      - name: Update package to patch version of package
        run: npm run package
      - name: Publish package to NPM
        run: npm publish
        working-directory: ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
